
Running BaselineExperiment. Run name: TMUXTRY2-default-2-35-AM-Jun-10-2023
Number of rows not filtered correctly (should be 0):  0
Length of dataset:  1733252
Num classes:  4850
Number of rows not filtered correctly (should be 0):  0
Length of dataset:  75418
Num classes:  4850
Number of rows not filtered correctly (should be 0):  0
Length of dataset:  89375
Num classes:  4850
Initializing model with 4850 num classes
Experiment running on device cuda
training for 10 epochs




























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































Epoch 1:  17%|██████████████████▏                                                                                     | 592/3386 [2:19:23<10:57:53, 14.13s/it]
Traceback (most recent call last):
  File "/home/rsikand/crisp/week10/baselines/species-classification/train.py", line 229, in <module>
    main(args)
  File "/home/rsikand/crisp/week10/baselines/species-classification/train.py", line 219, in main
    exp.train(num_epochs=args.epochs, display_batch_loss=args.batch_loss)
  File "/opt/conda/lib/python3.10/site-packages/torchplate/experiment.py", line 73, in train
    for batch in tqdm_loader:
  File "/opt/conda/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 240, 180] at entry 0 and [1, 240, 180] at entry 368